### ISSUE TITLE
csv exports fail for non-ascii distinct_ids

### ISSUE THREAD

**Issue by cassiegamm** [mixpanel/mixpanel_api#1]
csv exports fail for non-ascii distinct_ids with errors like: _UnicodeEncodeError: 'ascii' codec can't encode character u'\xe4' in position 22: ordinal not in range(128)_

to fix change 
https://github.com/mixpanel/mixpanel_api/blob/6d3fab496e1a01b83a59fb2d7bc72dd47c461af5/__init__.py#L1097 
to 

`row.append(item[initial_header_value].encode('utf-8'))`

**Comment by jaredmixpanel** [comment]
Thanks @cassiegamm - Fixed: https://github.com/mixpanel/mixpanel_api/commit/02d109515815eff719bff756e727aa74c3a03981
