### ISSUE TITLE
urllib2 breaks client using python3

### ISSUE THREAD

**Issue by gregorypease280** [mixpanel/mixpanel_api#10]
It appears that this client doesn't support python3 at the moment.

```
 from mixpanel_api import Mixpanel as MixPanelApi
  File "/mindshow/venvs/mindhole/lib/python3.6/site-packages/mixpanel_api/__init__.py", line 3, in <module>
    import urllib2  # for sending requests
ModuleNotFoundError: No module named 'urllib2'
```

https://github.com/mixpanel/mixpanel_api/blob/ee7eea50b1d7845b65e0db2b15f8d808569f7bdd/__init__.py#L3

relevant stackoverflow:
https://stackoverflow.com/questions/6594620/python-3-2-unable-to-import-urllib2-importerror-no-module-named-urllib2

**Comment by jaredmixpanel** [comment]
@gregorypease280 That is correct. This module is Python2 only, for now.

**Comment by gregorypease280** [comment]
@jaredmixpanel Cool, I think it would be helpful if the README was updated to reflect this. Also are you allowing the public to submit PRs?

**Comment by jaredmixpanel** [comment]
@gregorypease280 I've added a note to the README. Yes, you're welcome to submit a PR and we will review it.

**Comment by jin-beyond** [comment]
Is this fixed? I still meet this issue. I am using the latest release of sendgrid

**Comment by apurvis** [comment]
any progress on this?  python2 is officially deprecated in only a bit more than 2 months.

**Comment by jayharan** [comment]
yes any progress jared? @jaredmixpanel

**Comment by jaredmixpanel** [comment]
@jayharan i'm no longer the maintainer for this repo, it's @danakock. please see the existing py3 issue here: https://github.com/mixpanel/mixpanel_api/issues/12
