### ISSUE TITLE
'NoneType' object is not iterable when when 'request_per_day=True' and date range contains days w/o data

### ISSUE THREAD

**Issue by scott-marinoff** [mixpanel/mixpanel_api#11]
When using the 'request_per_day' _and_ the 'timezone_offset' query params, get the following error if a day in the date range supplied does not contain data:

> WARNING: /export API response empty
> Traceback (most recent call last):
>   File "events_export.py", line 10, in <module>
>     mixpanel.export_events('events backup.json', {'from_date':'2016-08-30','to_date':'2018-03-05'}, format='json', timezone_offset=8, add_gzip_header=True, request_per_day=True)
>   File "/usr/local/lib/python2.7/dist-packages/mixpanel_api/__init__.py", line 894, in export_events
>     for event in events:
> TypeError: 'NoneType' object is not iterable

Without the 'timezone_offset' query params, get expected '/export API response empty' message.

**Comment by jaredmixpanel** [comment]
@scott-marinoff Thanks for the report. I think I know the problem, I'll get this fixed as soon as I can.
