### ISSUE TITLE
export hits rate limits

### ISSUE THREAD

**Issue by 34code** [mixpanel/mixpanel_api#13]
current: people export runs into rate limits from server
expected: should export as advertised

**Comment by jaredmixpanel** [comment]
@34code you can lower the read_pool_size parameter to prevent running into rate limits, setting it to 2 or 3 will usually keep it slow enough to avoid the rate limits...

` mp = Mixpanel(api_secret, read_pool_size=3)`

We will consider lowering the default read_pool_size to prevent this out of the box

**Comment by 34code** [comment]
@jaredmixpanel thanks! I ran it on a 12 core machine :| (helpful to know how to configure)
