### ISSUE TITLE
allow people to provide a proxy

### ISSUE THREAD

**Issue by jtmcmc** [mixpanel/mixpanel_api#3]
Allow the option to provide a proxy server

**Comment by jaredmixpanel** [comment]
@jtmcmc @joeymalysz - It just dawned on me this can be done by simply re-assigning the values for the any of the base API URL properties, for example...

```
mp = Mixpanel(api_secret, token=project_token)
mp.IMPORT_API = 'https://myproxyserver.com'
```

You can do same for...

```
FORMATTED_API
RAW_API
BETA_IMPORT_API
```

https://github.com/mixpanel/mixpanel_api/blob/master/__init__.py#L40-L43
