### ISSUE TITLE
Is this de official python library?

### ISSUE THREAD

**Issue by dms90** [mixpanel/mixpanel_api#4]
Hi there,

Which is the official way to handle MixPanel via Python?
What about this repo? https://github.com/mixpanel/mixpanel-python

**Comment by jaredmixpanel** [comment]
@dms90 This library is used for exporting, modifying and importing Mixpanel data. It's a utility library for working with the various Mixpanel API's. For server-side event tracking with Python you will still use the mixpanel-python library: https://mixpanel.com/help/reference/python

**Comment by tdumitrescu** [comment]
This lib really needs a better name.

**Comment by jaredmixpanel** [comment]
@tdumitrescu noted. I'll sync with @jtmcmc on it.
