### ISSUE TITLE
export_events doesn't seem to work with the where filter

### ISSUE THREAD

**Issue by breadplop** [mixpanel/mixpanel_api#9]
Hi, I've been trying to export events out using the where filter but i keep getting this error TypeError: object of type 'NoneType' has no len()

**Comment by kathmath** [comment]
hi @breadplop, kathleen from the MP support team here. i just did a test and was able to use export_events with a where parameter so this might be related to your specific usage - the format i used looked like this:

`m.export_events('test_event_export.txt',{'from_date':'2018-01-01','to_date':'2018-02-05','event':'["Pageview"]', 'where': '(properties["$city"] == "Mountain View")'})`

if that doesn't help, you can write into support@mixpanel.com and i'd be happy to take a look for you. please include the code you're using and specify the project you're trying to export from. you can mention my name in your request so it gets routed to me :)
